# Generated by Django 4.2.1 on 2023-05-23 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats_server", "0006_alter_best_score_options_alter_stats_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="stats",
            table="stats",
        ),
    ]
