# Generated by Django 4.2.1 on 2023-05-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_server', '0007_alter_stats_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='best_score',
            options={'ordering': ['best_score']},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelTable(
            name='best_score',
            table='Best_score',
        ),
        migrations.AlterModelTable(
            name='stats',
            table='Stats',
        ),
    ]
