# Generated by Django 4.2 on 2023-06-11 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats_server", "0009_alter_stats_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Best_score",
            new_name="BestScore",
        ),
    ]
